### ISSUE TITLE
not support json string serialize and deserialize

### ISSUE THREAD

**Issue by Matrix-Zhang** [zonyitoo/bson-rs#58]
because of the mongodb use bson to store data, and the users just show and store the data, there is no need the json as middleware if bson support json string

**Comment by zonyitoo** [comment]
If I understand it correctly, what you want is removing `to_json` and `from_json` for BSON? That's impossible. It is necessary for mongo's shell.

BSON to JSON specification is defined [here](https://docs.mongodb.com/manual/reference/mongodb-extended-json/).

**Comment by Matrix-Zhang** [comment]
nope, for example, the web sent param as` "{"name":"elton", "female": false}"`, the web server's handle should use `to_bson(&param).to_extended_document()` to store in to mongodb directly, not convert to json first

**Comment by zonyitoo** [comment]
Why would you say that Bson will convert to JSON first?

**Comment by zonyitoo** [comment]
I would argue that this is not a real demand. Because it is your responsibility to convert the input string to `serde_json::Value`, not me.

As you can see in [`serde_json`'s document](https://docs.serde.rs/serde_json/index.html), it also provides

* `from_iter`
* `from_reader`
* `from_slice`
* `from_str`

for converting inputs to a `Value`, so I should also provide `Bson::from_json_iter`, `Bson::from_json_reader` ... bla bla. No. I don't think so.

**Comment by zonyitoo** [comment]
Closed for `rejected`.
