### ISSUE TITLE
ObjectId::to_hex doesn't return a lowercase string

### ISSUE THREAD

**Issue by Matrix-Zhang** [zonyitoo/bson-rs#60]
the last 0.2 version, this function return lowercase hex, and the mongodb shell use lowsercase too, In order to unify the style

maybe modify to:
```
hex::encode(&self.id).to_lowercase()
```

**Comment by zonyitoo** [comment]
This is because we use `ToHex` in `rustc-serialize` in `v0.2`, and now we have removed that crate.

cc @kyeah Should we make `to_hex()` return characters in lower case? https://github.com/zonyitoo/bson-rs/blob/master/src/oid.rs#L186

According to [data-encoding's document](http://ia0.github.io/data-encoding/data_encoding/base16/index.html), it actually uses `base16` as `hex` encoding, which can only use `0-9A-F`.

**Comment by zonyitoo** [comment]
Published as `v0.5.0`
