### ISSUE TITLE
error: mismatched typed

### ISSUE THREAD

**Issue by crashspringfield** [zonyitoo/bson-rs#91]
I'm trying to make sense of the following error: 

 expected struct `bson::ordered::OrderedDocument`, found a different struct `bson::ordered::OrderedDocument`
note: expected type `bson::ordered::OrderedDocument` (struct `bson::ordered::OrderedDocument`)
              found type `bson::ordered::OrderedDocument` (struct `bson::ordered::OrderedDocument`)
note: Perhaps two different versions of crate `bson` are being used?

Has the struct changed between versions?

**Comment by zonyitoo** [comment]
Nope. The reason is you cannot link one crate with multiple versions in your project.

The actual error message is the `OrderedDocument` that compiler expected is the `OrderedDocument` in that specific version of `bson`.

Solution is: check your `Cargo.lock`, find out all `bson` versions in your dependencies. Do not use precise version, such as `1.1.1`, in your own `Cargo.toml`.

**Comment by crashspringfield** [comment]
Thanks. I think I figured it out. The issue arose from me being imprecise in my `Cargo.toml`. I had `bson: "*"` but different dependencies I was using had specified different versions. One dependency was using 0.7 and another 0.10. Deleting my `Cargo.lock` and requiring 0.10 solved the issue.

Thanks for pointing me in the right direction!
